// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmiDMa0pkU3Gwa1t4CkkAYHKSd3_uxd40',
    appId: '1:169112403190:web:7d2c3777fce08834f300d7',
    messagingSenderId: '169112403190',
    projectId: 'flutter-chat-cfc59',
    authDomain: 'flutter-chat-cfc59.firebaseapp.com',
    storageBucket: 'flutter-chat-cfc59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGIaPSslUUUHgZd2CICLWXi7wPP3f3C0',
    appId: '1:169112403190:android:ff38deb7beda510cf300d7',
    messagingSenderId: '169112403190',
    projectId: 'flutter-chat-cfc59',
    storageBucket: 'flutter-chat-cfc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGn4CgGDw1d0ojhZtgXXaSplGHLP2V5qE',
    appId: '1:169112403190:ios:3126445eff416f07f300d7',
    messagingSenderId: '169112403190',
    projectId: 'flutter-chat-cfc59',
    storageBucket: 'flutter-chat-cfc59.appspot.com',
    iosBundleId: 'com.example.flutterMac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGn4CgGDw1d0ojhZtgXXaSplGHLP2V5qE',
    appId: '1:169112403190:ios:e4f3f7af6d9a4c78f300d7',
    messagingSenderId: '169112403190',
    projectId: 'flutter-chat-cfc59',
    storageBucket: 'flutter-chat-cfc59.appspot.com',
    iosBundleId: 'com.example.flutterMac.RunnerTests',
  );
}
